import solution
test_data = [l.strip() for l in '''............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............'''.split('\n') if len(l.strip())]

test_data2 = [l.strip() for l in '''
T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........'''.split('\n') if len(l.strip())]

def test_part_1():
    expected_part_1 = 14
    assert solution.part_1(test_data) == expected_part_1

def test_part_2():
    expected_part_2 = 34
    assert solution.part_2(test_data) == expected_part_2
def test_part_2_2():
    expected_part_2 = 9
    assert solution.part_2(test_data2) == expected_part_2
